-- Enrich existing companies only; retain employee profiles and commercial history.
BEGIN;
DO $review$
DECLARE entry record;
BEGIN
 FOR entry IN SELECT key, value FROM jsonb_each($profiles${"T1-dhaval-packaging-ltd":{"categories":["dairy"],"business":"manufacturer","opacity":"opaque","evidence":"Company overview describes its own injection-moulding production; catalogue includes dairy and food tubs. The RC550 photograph shows a coloured IML tub. Match opaque tub variants only and confirm the polymer and LIMEX trial with the factory.","source":"https://dhavalpackaging.com/overview","checkedOn":"2026-09-21","photos":[{"url":"https://dhavalpackaging.com/front/images/Round%20Container%20RC%20550.png","caption":"RC550 coloured IML food tub","source":"https://dhavalpackaging.com/overview"}]},"T3-star-plast-industries-pvt-ltd":{"categories":["bottles","jars"],"business":"manufacturer","opacity":"milky-white","evidence":"Company catalogue lists manufacture of white HDPE pharmaceutical bottles and jars. The matched company is at Shed 92, Makarpura GIDC. Photo shows its white HDPE jars; clear variants are excluded from this product match.","source":"https://www.starplasticindustries.com/hdpe-jar.html","checkedOn":"2026-09-21","photos":[{"url":"https://5.imimg.com/data5/SELLER/Default/2023/12/370140052/GG/US/XL/1521284/hdpe-pharmaceutical-bottles-250-ml-500x500.jpg","caption":"White HDPE pharmaceutical jars","source":"https://www.starplasticindustries.com/hdpe-jar.html"}]},"T3-metco-plastic-industries":{"categories":["bottles","jars"],"business":"manufacturer","opacity":"milky-white","evidence":"Manufacturer catalogue specifies white HDPE chemical bottles and white HDPE packaging jars. Company address matches Plot 107, Por Industrial Park. Target the opaque white HDPE line, with the selected grade and LIMEX trial confirmed by the factory.","source":"https://www.metcoplasticindustries.com/hdpe-bottle.html","checkedOn":"2026-09-21","photos":[{"url":"https://5.imimg.com/data5/SELLER/Default/2025/2/490419373/KX/CA/QI/7936473/hdpe-fine-chemical-bottles-500x500.jpg","caption":"White HDPE fine-chemical bottle","source":"https://www.metcoplasticindustries.com/hdpe-bottle.html"}]},"S27-itech-plast-india":{"categories":["toys"],"business":"manufacturer","opacity":"unknown","evidence":"Own website describes in-house injection-moulded toy production and decoration. The product image could not be reliably retrieved in this review; confirm an opaque toy variant before treating this as a qualified product match.","source":"https://itechplast.com/products/plastic-toys/","checkedOn":"2026-09-21","photos":[]},"N4-company-plast":{"categories":["bottles","jars"],"business":"unknown","opacity":"unknown","evidence":"Own catalogue uses manufacturing language but labels the business Trader - Wholesaler/Distributor. Confirm in-house production and an opaque product before qualification.","source":"https://www.company-plast.com/","checkedOn":"2026-09-21","photos":[]}}$profiles$::jsonb) LOOP
  INSERT INTO "RouteBookMark" ("stopId", "productProfile", "updatedAt")
  SELECT entry.key, entry.value::text, NOW()
  WHERE EXISTS (SELECT 1 FROM "RouteBookStop" WHERE id = entry.key AND "deletedAt" IS NULL)
  ON CONFLICT ("stopId") DO UPDATE SET "productProfile"=EXCLUDED."productProfile", "updatedAt"=NOW()
  WHERE "RouteBookMark"."productProfile" IS NULL;
 END LOOP;
END $review$;
COMMIT;
